README.md

Realised that my server was in the programming section. The programming tools are implemented as a complete server.

Add a-h/gemini to server list.

---

README.md

[gmnhg][gmnhg] is a tool that converts Hugo sites to Gemini sites (live site run with it: `gemini://tdem.in`). [md2gmn][md2gmn] is a tool that renders Markdown to Gemini pages. Both are included in a single repo (as both are based on the same renderer implementation hosted in this repo), so same link for both.
[gmnhg]: https://git.tdem.in/tdemin/gmnhg/src/branch/develop/cmd/gmnhg
[md2gmn]: https://git.tdem.in/tdemin/gmnhg/src/branch/develop/cmd/md2gmn

Add gmnhg / md2gmn

---

README.md

This is a small program that simplifies the process of converting entire sites with all their links from html 2 gemini

Add  Html2GeminiPy to tools

---

README.md

haven't seen that renderer does not keep gemini link
convert to http
(sorry)

correction in link to ergol

---

README.md

Transjovian is served by Phoebe which serves both Gemini and HTTPS, so
we can link to it directly.

Fix Transjovian link

---

README.md

rc-gemd is a simple rc script for hosting a gemini server on a plan9-based operating system.
I find rc-gemd pretty slick and probably the smallest server implementation i have seen to date.

Add rc-gemd

---

README.md

Include a link to the Gempub specification at https://codeberg.org/oppenlab/gempub. Gempub is an e-book and archive container specification. It is intended to serve as a container for e-books containing text files of in the "text/gemini" format, allowing the author to avoid the complexity of using web technologies for e-books that do not require them. It has a secondary purpose of functioning as an archival container for Gemini capsules.

Include link to the Gempub specification

---

README.md

As per title, add Telescope to the clients list.  Disclaimer: I'm the author.
Note: the same URL works both over https and gemini.

Add Telescope

---

README.md

Gemtexter moved from GitHub to Codeberg,
thank you very much!

Gemtexter moved from GitHub to Codeberg

---

README.md

The spec links you have on the README are to GitLab, where the in-progress specs are hosted. I think it's much more helpful to have a link to the actual official spec.
The layout I have now is kind of clumsy, feel to improve or let me know changes I can make.

Add official spec link

---

README.md

Adds TLGS (public search provider) and Dremini (C++ server/client) links.

Add TLGS and Dremini link

---

README.md

what the title says, I wrote the gemtext syntax highlighting plugin for [lite-xl](https://github.com/lite-xl/lite-xl), and thought that it belongs here.

added gemtext syntax highlighting for lite-xl

---

README.md

Current URL points to a dead page, project has moved to sourcehut

Fix URL for gemlog.sh

---

README.md

the previous link now points to a site with broken ssl that returns 404s. i've changed it to (what appears to be) the current repo url.

fix cgmnlm link

---

README.md

link updated according to the owner's message. the old repo says:
> NOTE: bollux's development has moved to tildegit.org. The new repo is here:
> tildegit.org/acdw/bollux

update bollux link

---

README.md

so that it displays as link in browsers

gem.awk client - change link from git to http

---

README.md

Proxy uses a forked version of Wobbly as its base

Adds an entry for the tildeverse gemini proxy

---

README.md

I would like to propose this addition to list of terminal clients.
It is a small CLI client called `gmi100` I wrote in 100 lines of C as a challenge for myself and for fun. It's actually usable with features similar to other small Gemini clients.
https://github.com/ir33k/gmi100

Add gmi100 to list of terminal clients

---

README.md

Also move gemget from programming to tools
since gemget is a command line tool
not a library.
close #179 opened by @zzo38

Add astroget

---

README.md

[gempost](https://github.com/justlark/gempost) (Rust) - Simple static site generator for Gemini blogs.

Add gempost

---

README.md

I created a tool to push gemlog posts into the Fediverse.

Add gemfreely to the tools list.

---

README.md

Adding Omura to Awesome Gemini terminal clients
Omura is a small-CLI small-client to access the [_Gemini Protocol_](https://geminiprotocol.net/) sites. A Gemtext-based Web Alternatives Protocol.
> Omura: 大村 / Large Village. It is a placename and surname found throughout Japan and the Ryūkyū Islands. The name listed in the Shinsen shōjiroku may be taken from a district in Hizen (now Nagasaki prefecture).
Omura is simple (Only commands, yes, commands.) and extensible (powered by UNIST AST and TypeScript) project to access the [_Gemini Protocol_](https://geminiprotocol.net/) sites, it's easy to use, you can run below than 5 minutes, thanks to JavaScript runtime engines.
```bash
bunx omura
NODE_TLS_REJECT_UNAUTHORIZED=0 bunx omura
```
```bash
npx omura
```
Omura takes heavy inspiration from …

chore(docs): Add omura

---

README.md

https://gitlab.com/clseibold/profectus
gemini://scrollprotocol.us.to/software/profectus/
Graphical browser (/document-viewer) that supports Gemini, Nex, Spartan, and Scroll.

Add Profectus browser.

---

README.md

Change gemini.circumlunar.space to the new address, geminiprotocol.net. Also remove https://transjovian.org/gemini that currently does not exist.

Change gemini.circumlunar.space to geminiprotocol.net

---

README.md

Vimini is a graphical browser, it isn't run from terminal.

Move vimini from Terminal to Graphical
