- README.md
Hello!
I'm submitting my Gemini server Titan; it's still under construction but it's in a working state now and I'd love input on how to improve it from the community! If it can help anyone out there that would be pretty cool too :) Idk if it's awesome but I'm pretty proud of what I've done so far. Thanks!
> Adding my Gemini server Titan

- README.md
Hello! I added a lot more of Gemini clients and tools. I also added periods (.) to every list item, and reorganized alphabetically some that were out of place. Here's an interesting client review in the Geminispace: gemini://kwiecien.us:1965/logarion/gemini-client-review.gmi
> Added a lot more of Gemini resources

- README.md
Hello! Here's another server, this one is written in CHICKEN Scheme.
> Add geminid (Scheme) server

- README.md
/cc @a-h (minor suggestion to @a-h: name it something else than name of protocol itself)
> add https://github.com/a-h/gemini

- README.md
> Add github.com/a-h/min browser

- README.md
The author of Två announced a name change to Ariane.
> Två renamed to Ariane

- README.md
Adding a server I started working on to the list.
> Add Earl Server to list of servers

- README.md
This list was missing mention of syntax highlighting, so that felt like a good addition. I also added a few services I maintain and updated the text to my client (which was already present on the list).
> Updates services and tools

- README.md
A (modest) personal project in its early steps. Gemini is awesome!
> Added Gemeaux Python server

- README.md
Adding https://github.com/cbrews/ignition: Gemini Protocol Client for Python Developers.
> Adding `ignition` to Programming resources

- README.md
A server I made in Nim. Pretty lightweight and has a bunch of features.
> Add Geminim server

- README.md
alphabetical order not impacted :)
> rename Gemini browser to Elaho

- README.md
> Add the Agunua Python library to README.md

- README.md
> Add the monitoring tool Manisha to README.md

- README.md
Do not include the default port
> Do not include the default network port 1965 in README.md

- README.md
Fix Ariane client homepage
Add Phaedra client
> Mobile: Fix Ariane, add Phaedra

- README.md
> Add gmi2html to tools

- README.md
Hi, I'm writing a Mastodon proxy for Gemini and I would like to share it with the community.
> Add MastoGem tool

- README.md
Hydepark is a discussion forum application for Gemini
> Added Hydepark to the list

- README.md
Add some tools static gemini site generators/frameworks for managing capsules or gemlogs
Add 1 tool, a sed script, to convert gemtext to html
Add 1 funcionnal client script in awk (yes it is awk and not gnu awk/gawk)
> add tools and 1 client

- README.md
As per title, add tinmop (a client), gempkg (a service) and gmid (a server).  Disclaimer: I'm the author of gempkg and gmid :)
> add tinmop, gempkg and gmid

- README.md
> Added Fossil client

- README.md
Just add yet another Gemtext blog engine to the awesome list.
> add gemtexter to tools

- README.md
> Update URL for twins server

- README.md
Added my own Gemini server, Moongem (https://sr.ht/~panda-roux/MoonGem)
> Adding MoomGem

- README.md
please see https://github.com/n0x1m/gmifs
> Add gmifs to servers

- README.md
> Added Gerbil client

- README.md
Add an entry for the galacteek browser
> Add an entry for galacteek

- README.md
> Gemtexter moved again to a different location

- README.md
Added it in response to https://github.com/kr1sp1n/awesome-gemini/issues/112
> Added Antenna

- README.md
https://github.com/aschuhardt/Opal
> Adding Opal

- README.md
- add Gemcurses
- add Buran
- add AV-98-fork
- remove Ariane (closes #107)
- remove gus.guru (closes #117)
> client updates

- README.md
Signed-off-by: Marek Küthe <m.k@mk16.de>
> add my gemini server

- README.md
I found the specification very interesting.
I found the tool quite handy when I created my own server. It illuminates many cases that one might not think of.
> Add a specification and a server test tool

- README.md
For some, using Git or GitHub can be difficult, so I've opened a PR for the two issues. Maybe the issues can be closed after that.
> solve issue #138 and issue #113 

- README.md
See: https://github.com/ranfdev/Geopard
> Adds Geopard (a GTK-based GUI client) by @ranfdev

- README.md
> Adds Mehari (Gemini server)

- README.md
- terminal clients: fix cgmnlm link, add astronaut, gelim, gmi, gemivim and vimini
- services: add kennedy and gemplex
- programming: add gusmobile, gemget and gmir
- servers: add laika
closes #162
> 5 new terminal clients, 3 new programming resources, 1 new server and 2 new services

- README.md
Updated the link to Bombadillo. Fixes #170.
> Update bombadillo link

- README.md
I noted in READEME.dm that amfora is in maintenance mode. Fixes #169
> Note amfora is in maintenance mode

- README.md
close #102 opened by @gskoljarev
Also mention that Galacteek also supports IPFS (close #168)
> Add AmiGemini.

- README.md
> Add dioscuri

- README.md
> Add SpaceBeans and some gemini services.

- README.md
Adds [gemini-server-clj](https://github.com/aburd/gemini-server-clj)
Checked out guidelines: https://github.com/kr1sp1n/awesome-gemini/blob/main/contributing.md
But the pull-request.md file is 404
> Adds gemini server

- README.md
Hi! I created a tool for converting Twine games to Gemtext that I felt like might be a useful addition.
> Add gemitwee to gemtext conversion tools

- README.md
Hi! 
I noticed that this library is not mentioned, even though it's quite mature and reliable. So here we go!
> Mention phos Commmon Lisp library&UI.

- README.md
The astro project was renamed to ereandel.
> Renamed astro to ereandel

- README.md
> add my project

- README.md
https://github.com/panicbit/twinstar/commit/982012cc2c0b39a096c068cd3eb86fe7da45281a
> northstar was renamed to twinstar

- README.md
add alhena client to cross-platform section
> add alhena client

- README.md
Add "GeminiFS", a FUSE filesystem for Gemini capsules that
uses LibreSSL and a connection pool. ISC license.
> Add "GeminiFS", a FUSE filesystem for Gemini capsules.
